#!/usr/bin/env bash
# One-command Floci local AWS sandbox bootstrap for web-gobbler.
# Preflight → start Floci → terraform apply (deploy_mode=floci) → push images →
# discover RDS/Redis → migrate → health-check → optional smoke test → report.
#
# Usage:
#   ./scripts/floci-up.sh
#   ./scripts/floci-up.sh --smoke-test
#   ./scripts/floci-up.sh --pg floci-rds-xxxx
#
# ponytail: push uses terraform ECR outputs (Floci registry on :5100).
set -euo pipefail

SMOKE_TEST=0
PG_CONTAINER=""
API_URL="${API_URL:-http://localhost:8080}"
READY_TIMEOUT_SEC="${READY_TIMEOUT_SEC:-120}"
HEALTH_TIMEOUT_SEC="${HEALTH_TIMEOUT_SEC:-180}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --smoke-test|-SmokeTest) SMOKE_TEST=1; shift ;;
    --pg|-Pg) PG_CONTAINER="${2:-}"; shift 2 ;;
    --api-url) API_URL="${2:-}"; shift 2 ;;
    --ready-timeout) READY_TIMEOUT_SEC="${2:-}"; shift 2 ;;
    --health-timeout) HEALTH_TIMEOUT_SEC="${2:-}"; shift 2 ;;
    -h|--help)
      sed -n '2,12p' "$0"
      exit 0
      ;;
    *) echo "Unknown arg: $1" >&2; exit 1 ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

step() { printf '\n==> %s\n' "$*"; }
warn() { printf 'WARNING: %s\n' "$*" >&2; }
abort() { printf 'ABORT: %s\n' "$*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1 || abort "$1 not found on PATH"; }

port_in_use() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "sport = :$port" 2>/dev/null | grep -q ":$port"
  else
    (echo >/dev/tcp/127.0.0.1/"$port") >/dev/null 2>&1
  fi
}

wait_http() {
  local url="$1" timeout="$2" pattern="${3:-}"
  local deadline=$((SECONDS + timeout)) body code
  while (( SECONDS < deadline )); do
    body="$(curl -sf -m 5 "$url" 2>/dev/null)" && code=$? || code=$?
    if [[ $code -eq 0 ]]; then
      if [[ -z "$pattern" ]] || grep -Eq "$pattern" <<<"$body"; then
        printf '%s\n' "$body"
        return 0
      fi
    fi
    sleep 2
  done
  return 1
}

tf_out() {
  local v
  v="$(terraform -chdir=terraform output -raw "$1" 2>/dev/null || true)"
  if [[ -z "$v" || "$v" == "null" ]]; then
    return 1
  fi
  printf '%s' "$v"
}

# ── Preflight ──────────────────────────────────────────────
step "Preflight"
need_cmd docker
need_cmd terraform
need_cmd aws
need_cmd curl
docker info >/dev/null 2>&1 || abort "docker daemon not reachable"
docker compose version >/dev/null 2>&1 || abort "docker compose not available"

svc="$(docker compose --profile sandbox ps --status running --services 2>/dev/null || true)"
floci_running=0
grep -qx 'floci' <<<"$svc" && floci_running=1
if [[ $floci_running -eq 0 ]] && port_in_use 4566; then
  abort "port 4566 is in use and Floci is not already running via compose profile sandbox"
fi

# ── Start ──────────────────────────────────────────────────
step "Start Floci (compose profile sandbox)"
docker compose --profile sandbox up --detach floci

# ── Ready ──────────────────────────────────────────────────
step "Wait for Floci health (max ${READY_TIMEOUT_SEC}s)"
wait_http "http://localhost:4566/_localstack/health" "$READY_TIMEOUT_SEC" >/dev/null \
  || abort "timed out waiting for Floci /_localstack/health"
echo "Floci ready."

# ── Env ────────────────────────────────────────────────────
step "Set Floci AWS env"
export AWS_ENDPOINT_URL="http://localhost:4566"
export AWS_ACCESS_KEY_ID="test"
export AWS_SECRET_ACCESS_KEY="test"
export AWS_DEFAULT_REGION="us-east-1"
export AWS_EC2_METADATA_DISABLED="true"

backend_floci="$REPO_ROOT/terraform/backend.floci.hcl"
if [[ ! -f "$backend_floci" ]]; then
  step "Write terraform/backend.floci.hcl"
  cat >"$backend_floci" <<'EOF'
# Backend config for deploy_mode=floci (generated by scripts/floci-up.sh).
endpoint   = "http://localhost:4566"
region     = "us-east-1"
bucket     = "goscrape-terraform-state"
key        = "goscrape/terraform.tfstate"
access_key = "test"
secret_key = "test"

skip_credentials_validation = true
skip_region_validation      = true
skip_requesting_account_id  = true
force_path_style            = true
EOF
fi

step "Ensure terraform state bucket in Floci S3"
aws --endpoint-url http://localhost:4566 s3 mb s3://goscrape-terraform-state >/dev/null 2>&1 || true

# ── Apply ──────────────────────────────────────────────────
step "Terraform init + apply (deploy_mode=floci)"
terraform -chdir=terraform init -backend-config=backend.floci.hcl -input=false -reconfigure
terraform -chdir=terraform plan -var "deploy_mode=floci" -input=false -out=floci.tfplan
terraform -chdir=terraform apply -auto-approve -input=false floci.tfplan

# ── Push ───────────────────────────────────────────────────
step "Build + push api/worker images"
push_warned=0
api_repo="$(tf_out ecr_api_repository_url || true)"
worker_repo="$(tf_out ecr_worker_repository_url || true)"
if [[ -z "$api_repo" || -z "$worker_repo" ]]; then
  warn "ECR repository URLs empty from terraform outputs; skipping push"
  push_warned=1
else
  if ! {
    docker build -t "${api_repo}:latest" -f docker/Dockerfile.api . \
      && docker build -t "${worker_repo}:latest" -f docker/Dockerfile.worker . \
      && docker push "${api_repo}:latest" \
      && docker push "${worker_repo}:latest"
  }; then
    warn "image push failed (continuing)"
    push_warned=1
  else
    cluster="$(tf_out ecs_cluster_name || true)"
    api_svc="$(tf_out ecs_api_service_name || true)"
    worker_svc="$(tf_out ecs_worker_service_name || true)"
    aws --endpoint-url http://localhost:4566 ecs update-service \
      --cluster "$cluster" --service "$api_svc" --force-new-deployment >/dev/null 2>&1 || true
    aws --endpoint-url http://localhost:4566 ecs update-service \
      --cluster "$cluster" --service "$worker_svc" --force-new-deployment >/dev/null 2>&1 || true
    echo "Waiting for ECS api container to publish :8080..."
    deadline=$((SECONDS + 90))
    while (( SECONDS < deadline )); do
      if docker ps --format '{{.Names}} {{.Ports}}' | grep -qE 'floci-ecs-.*-api.*8080'; then
        break
      fi
      sleep 3
    done
  fi
fi

# ── Discover ───────────────────────────────────────────────
step "Discover RDS/Redis endpoints"
rds_host="$(tf_out rds_host)" || abort "RDS host empty from terraform outputs"
rds_port="$(tf_out rds_port)" || abort "RDS port empty from terraform outputs"
redis_host="$(tf_out redis_host)" || abort "Redis host empty from terraform outputs"
redis_port="$(tf_out redis_port)" || abort "Redis port empty from terraform outputs"
if api_url_out="$(tf_out api_url 2>/dev/null)"; then
  API_URL="$api_url_out"
fi

rds_json="$(aws --endpoint-url http://localhost:4566 rds describe-db-instances --output json 2>/dev/null || true)"
redis_json="$(aws --endpoint-url http://localhost:4566 elasticache describe-replication-groups --output json 2>/dev/null || true)"
grep -q 'DBInstances' <<<"$rds_json" || abort "aws rds describe-db-instances returned nothing usable"
grep -q 'ReplicationGroups' <<<"$redis_json" || abort "aws elasticache describe-replication-groups returned nothing usable"
echo "RDS  = ${rds_host}:${rds_port}"
echo "Redis= ${redis_host}:${redis_port}"

valkey_name="$(docker ps --format '{{.Names}}' | grep -E '^floci-valkey-' | head -n1 || true)"
[[ -n "$valkey_name" ]] || abort "Floci Valkey container floci-valkey-* is not running. Try: terraform -chdir=terraform apply -replace=aws_elasticache_replication_group.redis -var deploy_mode=floci"
echo "Valkey container: $valkey_name"

# ── Migrate ────────────────────────────────────────────────
step "Apply migrations into Floci RDS"
mig_file="$REPO_ROOT/migrations/000001_create_jobs_table.up.sql"
[[ -f "$mig_file" ]] || abort "missing $mig_file"

if [[ -z "$PG_CONTAINER" ]]; then
  PG_CONTAINER="$(docker ps --format '{{.Names}}' | grep -E '^floci-rds-' | head -n1 || true)"
fi
[[ -n "$PG_CONTAINER" ]] || abort "could not find floci-rds-* container; pass --pg <name>"

# Floci RDS listens inside the container on 5432
docker exec -i "$PG_CONTAINER" \
  psql "postgres://goscrape_admin:devpass@127.0.0.1:5432/goscrape" \
  -v ON_ERROR_STOP=1 -f - <"$mig_file" \
  || abort "migration failed via docker exec $PG_CONTAINER"
echo "Migration applied via $PG_CONTAINER"

# ── Health ─────────────────────────────────────────────────
step "Poll API health ($API_URL/api/v1/health)"
health_ok=0
deadline=$((SECONDS + HEALTH_TIMEOUT_SEC))
while (( SECONDS < deadline )); do
  if health_body="$(curl -sf -m 5 "$API_URL/api/v1/health" 2>/dev/null)"; then
    if grep -q '"db"[[:space:]]*:[[:space:]]*"ok"' <<<"$health_body" \
      && grep -q '"redis"[[:space:]]*:[[:space:]]*"ok"' <<<"$health_body"; then
      echo "$health_body"
      health_ok=1
      break
    fi
  fi
  sleep 2
done
if [[ $health_ok -eq 0 ]]; then
  echo "HEALTH FAILED: timed out waiting for $API_URL/api/v1/health" >&2
fi

# ── Smoke (optional) ───────────────────────────────────────
smoke_status="skipped"
if [[ $SMOKE_TEST -eq 1 ]]; then
  step "SmokeTest: POST /api/v1/scrape → poll completed"
  smoke_status="FAILED"
  body='{"url":"https://example.com","extract":["links"]}'
  if create="$(curl -sf -m 30 -X POST "$API_URL/api/v1/scrape" -H 'Content-Type: application/json' -d "$body")"; then
    job_id="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("job_id") or "")' <<<"$create" 2>/dev/null || true)"
    if [[ -z "$job_id" ]]; then
      echo "SMOKE FAILED: no job_id in scrape response: $create" >&2
    else
      deadline=$((SECONDS + 120))
      final=""
      while (( SECONDS < deadline )); do
        final="$(curl -sf -m 10 "$API_URL/api/v1/jobs/$job_id" || true)"
        status="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' <<<"$final" 2>/dev/null || true)"
        if [[ "$status" == "completed" || "$status" == "failed" ]]; then
          break
        fi
        sleep 2
      done
      status="$(python3 -c 'import json,sys; print(json.load(sys.stdin).get("status",""))' <<<"$final" 2>/dev/null || true)"
      has_results="$(python3 -c 'import json,sys; d=json.load(sys.stdin); print("1" if d.get("results") else "0")' <<<"$final" 2>/dev/null || echo 0)"
      if [[ "$status" == "completed" && "$has_results" == "1" ]]; then
        echo "Smoke OK job_id=$job_id status=completed"
        smoke_status="ok"
      else
        echo "SMOKE FAILED: job $job_id status=$status" >&2
      fi
    fi
  else
    echo "SMOKE FAILED: POST /api/v1/scrape failed" >&2
  fi
fi

# ── Report ─────────────────────────────────────────────────
step "Report"
health_label="FAILED"
[[ $health_ok -eq 1 ]] && health_label="ok"
push_label="ok"
[[ $push_warned -eq 1 ]] && push_label="warned / skipped"

cat <<EOF
Floci sandbox ready (local AWS, \$0)

  API URL     : $API_URL
  Health      : $API_URL/api/v1/health ($health_label)
  RDS         : ${rds_host}:${rds_port}  user=goscrape_admin pass=devpass db=goscrape
  Redis       : ${redis_host}:${redis_port}  (auth token=devpass when required)
  ECR API     : ${api_repo:-}
  ECR Worker  : ${worker_repo:-}
  Push        : $push_label
  SmokeTest   : $smoke_status

Teardown:
  docker compose --profile sandbox down -v

Re-run this script anytime; terraform apply is idempotent under deploy_mode=floci.
EOF

[[ $health_ok -eq 1 ]] || exit 2
if [[ $SMOKE_TEST -eq 1 && "$smoke_status" != "ok" ]]; then
  exit 3
fi
exit 0
